cli:
  - "cli/**/*"

dist:
  - "dist/**/*"

types:
  - "types/**/*"

package: 
  - "package.json"

cicd:
  - ".github/**/*"

wip:
  - "**/*"

docker:
  - ".docker/**/*"
  
md:
  - "README.md"
  - "CODEOFCONDUCT.md"
  - "CONTRIBUTING.md"